site_name: Izzat Mukhanov
site_url: https://izzatbek.github.io
repo_url: https://github.com/izzatbek

theme: yeti
theme_dir: ./custom_theme

site_description: Izzatbek Mukhanov's personal web site
site_author: Izzat Mukhanov

pages:
    - 'Home': 'index.md'
    - 'En Fran√ßais': 'cv_francais.md'